

(define
 (problem CYCLE_WEEKLY2)
 (:domain CYCLE_WEEKLY2)
 (:objects towel_3 towel_2 towel_1 - towel wallet sleeping_bag shirts shampoo padlock hair_trimmers hair_brush food_cans can_opener camouflage - stuff woodmans walmart_oswego tigerdirect starbucks_aurora frys cvs_indian_trail_and_orchard caribou_coffee_batavia - store landing_to_second_floor_stairwell first_floor_to_landing_stairwell entry_to_first_floor_stairwell basement_to_entry_stairwell - stairwell utility_room garage crawl_space balcony - space upstairs_shower - shower clothing_grey_shirt_2 clothing_grey_shirt_1 clothing_green_shirt_1 clothing_blue_shirt_1 - shirt living_room kitchen dining_room bedroom - room andrew_dougherty - person front_door balcony_door - perimeter_door clothing_khaki_shorts_2 clothing_khaki_shorts_1 - pants upstairs_bathroom_outlets kitchen_outlets den_outlets - outlet den - officeroom meal_velveeta_shells_and_cheese meal_pindi_chana meal_palek_paneer meal_miso_soup - mealtype laptop_backpack - lockable_container outside - location upstairs_washer - laundry_washing_machine laundry_load - laundry_load upstairs_dryer - laundry_dryer_machine columcille_computer - laptop second_floor_landing landing - landing finger_clippers - hygiene_tool garage_entry_way entry - entry_way electric_razor_0 - electric_razor garage_door den_door crawl_space_door basement_door - door computer_desk - desk Wednesday Tuesday Thursday Sunday Saturday Monday Friday - day_of_week Wednesday Tuesday Thursday Sunday Saturday Monday Friday - day date_20120828 date_20120827 date_20120826 date_20120825 date_20120824 date_20120823 date_20120822 date_20120821 - date dennis_computer - computer landing_closet kitchen_closet dining_room_closet coat_closet bedroom_closet - closet townhome - building guestbed couch - bed cell_phone bluetooth_headset - battery_powered_device upstairs_bathroom guest_bathroom - bathroom)
 (:init
  (= (actions) 0)
  (= (cash andrew_dougherty) 49)
  (= (charge_level bluetooth_headset) 0.3)
  (= (charge_level cell_phone) 0.1)
  (= (charge_level columcille_computer) 1)
  (= (charge_level electric_razor_0) 0.0)
  (= (charge_rate bluetooth_headset) 0.5)
  (= (charge_rate cell_phone) 1)
  (= (charge_rate columcille_computer) 0.6)
  (= (charge_rate electric_razor_0) 0.5)
  (= (discharge_rate bluetooth_headset) 0.01)
  (= (discharge_rate cell_phone) 0.07)
  (= (discharge_rate columcille_computer) 0.3)
  (= (discharge_rate electric_razor_0) 2.5)
  (= (fee_for_use upstairs_dryer) 0)
  (= (fee_for_use upstairs_washer) 0)
  (= (hours_worked_on_date Andrew_Dougherty date_20120821) 0)
  (= (hours_worked_on_date Andrew_Dougherty date_20120822) 0)
  (= (hours_worked_on_date Andrew_Dougherty date_20120823) 0)
  (= (hours_worked_on_date Andrew_Dougherty date_20120824) 0)
  (= (how_filling meal_miso_soup Andrew_Dougherty) 0.7)
  (= (how_filling meal_palek_paneer Andrew_Dougherty) 0.4)
  (= (how_filling meal_pindi_chana Andrew_Dougherty) 0.4)
  (= (how_filling meal_velveeta_shells_and_cheese Andrew_Dougherty) 1.0)
  (= (hunger_level andrew_dougherty) 1)
  (= (quantity meal_miso_soup kitchen_closet) 3)
  (= (quantity meal_palek_paneer kitchen_closet) 2)
  (= (quantity meal_pindi_chana kitchen_closet) 2)
  (= (quantity meal_velveeta_shells_and_cheese kitchen_closet) 1)
  (= (rate_of_eating Andrew_Dougherty) 5.0)
  (= (speed andrew_dougherty) 1)
  (= (total_walking_distance) 0)
  (at_location andrew_dougherty den)
  (at_location balcony townhome)
  (at_location basement_to_entry_stairwell townhome)
  (at_location bedroom townhome)
  (at_location bedroom_closet townhome)
  (at_location clothing_blue_shirt_1 bedroom)
  (at_location clothing_green_shirt_1 bedroom)
  (at_location clothing_grey_shirt_1 bedroom)
  (at_location clothing_grey_shirt_2 bedroom)
  (at_location clothing_khaki_shorts_1 bedroom)
  (at_location clothing_khaki_shorts_2 bedroom)
  (at_location coat_closet townhome)
  (at_location columcille_computer living_room)
  (at_location computer_desk den)
  (at_location couch living_room)
  (at_location crawl_space townhome)
  (at_location den townhome)
  (at_location den_outlets den)
  (at_location dennis_computer den)
  (at_location dining_room townhome)
  (at_location dining_room_closet townhome)
  (at_location electric_razor_0 upstairs_bathroom)
  (at_location entry townhome)
  (at_location entry_to_first_floor_stairwell townhome)
  (at_location finger_clippers den)
  (at_location first_floor_to_landing_stairwell townhome)
  (at_location garage townhome)
  (at_location garage_entry_way townhome)
  (at_location guest_bathroom townhome)
  (at_location guestbed bedroom)
  (at_location kitchen townhome)
  (at_location kitchen_closet townhome)
  (at_location kitchen_outlets kitchen)
  (at_location landing townhome)
  (at_location landing_closet townhome)
  (at_location landing_to_second_floor_stairwell townhome)
  (at_location laptop_backpack den)
  (at_location laundry_load bedroom)
  (at_location living_room townhome)
  (at_location second_floor_landing townhome)
  (at_location towel_1 bedroom)
  (at_location towel_2 bedroom)
  (at_location towel_3 bedroom)
  (at_location upstairs_bathroom townhome)
  (at_location upstairs_bathroom_outlets upstairs_bathroom)
  (at_location upstairs_dryer utility_room)
  (at_location upstairs_shower upstairs_bathroom)
  (at_location upstairs_washer utility_room)
  (at_location utility_room townhome)
  (autonomous andrew_dougherty)
  (day_of_week date_20120821 Tuesday)
  (day_of_week date_20120822 Wednesday)
  (day_of_week date_20120823 Thursday)
  (day_of_week date_20120824 Friday)
  (day_of_week date_20120825 Saturday)
  (day_of_week date_20120826 Sunday)
  (day_of_week date_20120827 Monday)
  (day_of_week date_20120828 Tuesday)
  (dirty clothing_blue_shirt_1)
  (dirty clothing_green_shirt_1)
  (dirty clothing_grey_shirt_1)
  (dirty clothing_grey_shirt_2)
  (dirty clothing_khaki_shorts_1)
  (dirty clothing_khaki_shorts_2)
  (dirty den)
  (dirty garage)
  (dirty towel_1)
  (dirty towel_2)
  (dirty towel_3)
  (dirty upstairs_bathroom)
  (exhausted andrew_dougherty)
  (has_door balcony_door balcony dining_room)
  (has_door basement_door garage garage_entry_way)
  (has_door crawl_space_door crawl_space garage_entry_way)
  (has_door den_door den garage_entry_way)
  (has_door front_door entry outside)
  (has_door garage_door garage outside)
  (has_permission_to_use Andrew_Dougherty upstairs_bathroom)
  (locked_door basement_door)
  (locked_door front_door)
  (locked_door garage_door)
  (mobile bluetooth_headset)
  (mobile cell_phone)
  (mobile clothing_blue_shirt_1)
  (mobile clothing_green_shirt_1)
  (mobile clothing_grey_shirt_1)
  (mobile clothing_grey_shirt_2)
  (mobile clothing_khaki_shorts_1)
  (mobile clothing_khaki_shorts_2)
  (mobile columcille_computer)
  (mobile electric_razor_0)
  (mobile finger_clippers)
  (mobile laptop_backpack)
  (mobile laundry_load)
  (mobile towel_1)
  (mobile towel_2)
  (mobile towel_3)
  (plugged_in dennis_computer)
  (wearing Andrew_Dougherty clothing_grey_shirt_1)
  (wearing Andrew_Dougherty clothing_khaki_shorts_1))
 (:goal
  (and
   (ready_for_work Andrew_Dougherty)))
 (:metric minimize
  (total-time)))