
; Version LPG-td-1.0
; Seed 10413993
; Command line: /var/lib/myfrdcsa/codebases/internal/verber/data/planner-library/lpg-td-1.0 -o mealplanning/caloriesingle/current/caloriesingle.d.pddl -f mealplanning/caloriesingle/current/caloriesingle.p.pddl -out /var/lib/myfrdcsa/codebases/internal/verber/data/worldmodel/worlds/mealplanning/caloriesingle/current/caloriesingle.p.pddl.LPG.sol -speed 
; Problem mealplanning/caloriesingle/current/caloriesingle.p.pddl
; Time 0.00
; Search time 0.00
; Parsing time 0.00
; Mutex time 0.00
; MetricValue 1620.50

0.0003:   (PURCHASE ANDREWDOUGHERTY BEEFRAVIOLI_CHEFBOYARDEE BEEFRAVIOLI_CHEFBOYARDEE1 WALMART1) [0.1000]
0.1005:   (CONSUME ANDREWDOUGHERTY BEEFRAVIOLI_CHEFBOYARDEE BEEFRAVIOLI_CHEFBOYARDEE1 WALMART1) [0.1000]
0.0008:   (PURCHASE ANDREWDOUGHERTY TRADITIONALSPLITPEAWITHHAM_PROGRESSO TRADITIONALSPLITPEAWITHHAM_PROGRESSO1 WALMART1) [0.1000]
0.2010:   (CONSUME ANDREWDOUGHERTY TRADITIONALSPLITPEAWITHHAM_PROGRESSO TRADITIONALSPLITPEAWITHHAM_PROGRESSO1 WALMART1) [0.1000]
0.0012:   (PURCHASE ANDREWDOUGHERTY MACANDCHEESE_CHEFBOYARDEE MACANDCHEESE_CHEFBOYARDEE1 WALMART1) [0.1000]
0.3015:   (CONSUME ANDREWDOUGHERTY MACANDCHEESE_CHEFBOYARDEE MACANDCHEESE_CHEFBOYARDEE1 WALMART1) [0.1000]
0.0018:   (PURCHASE ANDREWDOUGHERTY SPAGHETTIRINGSPASTAWITHMEATBALLS_GREATVALUE SPAGHETTIRINGSPASTAWITHMEATBALLS_GREATVALUE1 WALMART1) [0.1000]
0.4020:   (CONSUME ANDREWDOUGHERTY SPAGHETTIRINGSPASTAWITHMEATBALLS_GREATVALUE SPAGHETTIRINGSPASTAWITHMEATBALLS_GREATVALUE1 WALMART1) [0.1000]
0.5023:   (ISREPLETE ANDREWDOUGHERTY) [0.1000]


