#!/usr/bin/perl -w

# BE THE MASTER OF YOURSELF

# basically, the system accomplishes,  in whatever ways necessary what
# is  intended to  be  performed by  the "domain.lisp"  file.

use Data::Dumper;

my $domain;
my $tasks = {};
my $actions = {};
my $task2action = {};
$domainfile = "/home/mburch/lightspeed/domain.lisp";

sub SaveDomain {
  SaveDataToFile(File => $domainfile,
		 Data => $domain);
}

sub LoadDomain {
  LoadDataFromFile(File => $domainfile,
		   Data => $domain);
}

sub SaveDataToFile {
  my (%args) = (@_);
  my $OUT;
  open (OUT, ">$args{File}")  or die "ouch\n";
  print OUT Dumper($args{Data});
  close (OUT);
}

sub LoadDataFromFile {
  my (%args) = (@_);
  my $c = `cat "$args{File}"`;
  $args{Data} = eval $c;
}

sub PrintDomain {
  print Dumper($domain);
}

sub ProcessInput {
  
}

sub WalkThrough {
  # program to walk through constraints
}

sub ShowCurrentDomain {

}

sub ReportEvent {

}

sub InOrderTraverseDomain {
  my @q = ();
  my @l = ();
  my @tasks = ();
  push @q, @$domain;
  while (@q) {
    my $x = shift @q;
    if (ref $x eq "ARRAY") {
      if ($x->[0] eq "task") {
	push @tasks, $x;
      }
      unshift @q, @$x;
    } else {
      push @l, $x;
    }
  }
  print Dumper([@tasks]);
}



sub ParseDomainFile {
  my (%args) = (@_);
  my $domainfile = $args{DomainFile};
  my $c = `cat "$domainfile"`;
  $c =~ s/;.*//mg;
  my $tokens = [split //,$c];
  my $cnt = 0;
  my $stack = [];
  my $symbol = "";
  do {
    $char = shift @$tokens;
    if ($char =~ /\(/) {
      ++$cnt;
      $stack->[$cnt] = [];
      $symbol = "";
    } elsif ($char =~ /[\s\n]/) {
      if (length $symbol) {
	push @{$stack->[$cnt]},$symbol;
	$symbol = "";
      }
    } elsif ($char =~ /\)/) {
      # now $stack->[$cnt] holds all of  our objects, and so just have
      # to move those into the right place
      if (length $symbol) {
	push @{$stack->[$cnt]},$symbol;
	$symbol = "";
      }
      my @a = @{$stack->[$cnt]};
      $stack->[$cnt] = undef;
      --$cnt;
      push @{$stack->[$cnt]}, \@a;
    } else {
      if ($char !~ /\s/) {
	$symbol .= $char;
      }
    }
  } while (@$tokens);
  $domain = $stack->[0];
}

sub Generate {
  my (%args) = (@_);
  my $structure = $args{Structure};
  my @res = ();
  foreach my $x (@$structure) {
    if (ref $x eq "ARRAY") {
      push @res, Generate(Structure => $x);
    } else {
      push @res, $x;
    }
  }
  return "(". join(" ",@res).")";
}

sub ExportCurrentDomain {

}

sub ExportCurrentWorldModel {

}

sub LoadCurrentWorldModel {

}

sub SaveCurrentWorldModel {

}

sub DeclareTask {
  my (%args) = (@_);
  my $task = $args{Task};
  # check that its not a complex task
  my $complex = 0;
  foreach my $e (@$task) {
    if (ref $e eq "ARRAY") {
      $complex = 1;
    }
  }

  if (! $complex) {
    my @s = @$task;
    shift @s;
    my $action = $task->[1];
    if (! exists $actions->{$action}) {
      print "Declaring action: $action\n";
      $actions->{$action} = 1;
      $task2action->{$action} = {};
    }

    my $taskdescription = join(" ",@s);
    if (! exists $tasks->{$taskdescription}) {
      print "Declaring task: $taskdescription\n";
      $tasks->{$taskdescription} = $task;
      $task2action->{$task->[1]}->{$taskdescription} = 1;
    }
  } else {
    print "Declaring complex task: ".$task->[1]."\n";
  }
}

sub EvalDomain {
  my (%args) = (@_);
  my $dm = $args{Domain};
  my @q = ();
  my @l = ();
  my @tasks = ();
  push @q, @$dm;
  while (@q) {
    my $x = shift @q;
    if (ref $x eq "ARRAY") {
      if ($x->[0] eq "task") {
	DeclareTask(Task => $x);
	push @tasks, $x;
      }
      unshift @q, @$x;
    } else {
      push @l, $x;
    }
  }
  # print Dumper([@tasks]);
}

sub PrintWorld {
  print Dumper($task2action);
}

ParseDomainFile
  (DomainFile => $domainfile);
# InOrderTraverseDomain;
# print Generate(Structure => $domain);
EvalDomain(Domain => $domain);
PrintWorld;
