

(define
 (problem date-20120902)
 (:domain date-20120902)
 (:objects towel-3 towel-2 towel-1 - towel wallet sleeping-bag shirts shampoo padlock hair-trimmers hair-brush food-cans can-opener camouflage - stuff woodmans walmart-oswego tigerdirect starbucks-aurora frys cvs-indian-trail-and-orchard caribou-coffee-batavia - store landing-to-second-floor-stairwell first-floor-to-landing-stairwell entry-to-first-floor-stairwell basement-to-entry-stairwell - stairwell utility-room garage crawl-space balcony - space upstairs-shower - shower clothing-grey-shirt-2 clothing-grey-shirt-1 clothing-green-shirt-1 clothing-blue-shirt-1 - shirt living-room kitchen dining-room bedroom - room andrew-dougherty - person front-door balcony-door - perimeter-door clothing-khaki-shorts-2 clothing-khaki-shorts-1 - pants upstairs-bathroom-outlets kitchen-outlets den-outlets - outlet den - officeroom den - office meal-velveeta-shells-and-cheese meal-pindi-chana meal-palek-paneer meal-miso-soup - mealtype laptop-backpack - lockable-container outside - location upstairs-washer - laundry-washing-machine laundry-load - laundry-load upstairs-dryer - laundry-dryer-machine columcille-computer - laptop second-floor-landing landing - landing towel-3 towel-2 towel-1 shampoo finger-clippers - hygiene-tool garage-entry-way entry - entry-way electric-razor-0 - electric-razor garage-door den-door crawl-space-door basement-door - door computer-desk - desk Wednesday Tuesday Thursday Sunday Saturday Monday Friday - day date-20120827 date-20120826 date-20120825 date-20120824 date-20120823 date-20120822 date-20120821 - date dennis-computer - computer landing-closet kitchen-closet dining-room-closet coat-closet bedroom-closet - closet townhome - building guestbed couch - bed cell-phone bluetooth-headset - battery-powered-device upstairs-bathroom guest-bathroom - bathroom)
 (:init
  (= (actions) 0)
  (= (cash andrew-dougherty) 49)
  (= (charge-level bluetooth-headset) 0.3)
  (= (charge-level cell-phone) 0.1)
  (= (charge-level columcille-computer) 1)
  (= (charge-level electric-razor-0) 0.0)
  (= (charge-rate bluetooth-headset) 0.5)
  (= (charge-rate cell-phone) 1)
  (= (charge-rate columcille-computer) 0.6)
  (= (charge-rate electric-razor-0) 0.5)
  (= (discharge-rate bluetooth-headset) 0.01)
  (= (discharge-rate cell-phone) 0.07)
  (= (discharge-rate columcille-computer) 0.3)
  (= (discharge-rate electric-razor-0) 2.5)
  (= (fee-for-use upstairs-dryer) 0)
  (= (fee-for-use upstairs-washer) 0)
  (= (hours-worked-on-date Andrew-Dougherty date-20120821) 0)
  (= (hours-worked-on-date Andrew-Dougherty date-20120822) 0)
  (= (hours-worked-on-date Andrew-Dougherty date-20120823) 0)
  (= (hours-worked-on-date Andrew-Dougherty date-20120824) 0)
  (= (how-filling meal-miso-soup Andrew-Dougherty) 0.7)
  (= (how-filling meal-palek-paneer Andrew-Dougherty) 0.4)
  (= (how-filling meal-pindi-chana Andrew-Dougherty) 0.4)
  (= (how-filling meal-velveeta-shells-and-cheese Andrew-Dougherty) 1.0)
  (= (hunger-level andrew-dougherty) 1)
  (= (quantity meal-miso-soup kitchen-closet) 3)
  (= (quantity meal-palek-paneer kitchen-closet) 2)
  (= (quantity meal-pindi-chana kitchen-closet) 2)
  (= (quantity meal-velveeta-shells-and-cheese kitchen-closet) 1)
  (= (rate-of-eating Andrew-Dougherty) 5.0)
  (= (speed andrew-dougherty) 1)
  (= (total-walking-distance) 0)
  (at 0 (inaccessible walmart-oswego))
  (at 0 (isolated living-room))
  (at 0 (today date-20120821))
  (at 120 (not (today date-20120825)))
  (at 120 (today date-20120826))
  (at 144 (not (today date-20120826)))
  (at 144 (today date-20120827))
  (at 168 (not (today date-20120827)))
  (at 23 (isolated living-room))
  (at 24 (not (today date-20120821)))
  (at 24 (today date-20120822))
  (at 31 (not (isolated living-room)))
  (at 48 (not (today date-20120822)))
  (at 48 (today date-20120823))
  (at 7 (not (inaccessible walmart-oswego)))
  (at 7 (not (isolated living-room)))
  (at 72 (not (today date-20120823)))
  (at 72 (today date-20120824))
  (at 96 (not (today date-20120824)))
  (at 96 (today date-20120825))
  (at-location andrew-dougherty den)
  (at-location balcony townhome)
  (at-location basement-to-entry-stairwell townhome)
  (at-location bedroom townhome)
  (at-location bedroom-closet townhome)
  (at-location clothing-blue-shirt-1 bedroom)
  (at-location clothing-green-shirt-1 bedroom)
  (at-location clothing-grey-shirt-1 bedroom)
  (at-location clothing-grey-shirt-2 bedroom)
  (at-location clothing-khaki-shorts-1 bedroom)
  (at-location clothing-khaki-shorts-2 bedroom)
  (at-location coat-closet townhome)
  (at-location columcille-computer living-room)
  (at-location computer-desk den)
  (at-location couch living-room)
  (at-location crawl-space townhome)
  (at-location den townhome)
  (at-location den-outlets den)
  (at-location dennis-computer den)
  (at-location dining-room townhome)
  (at-location dining-room-closet townhome)
  (at-location electric-razor-0 upstairs-bathroom)
  (at-location entry townhome)
  (at-location entry-to-first-floor-stairwell townhome)
  (at-location finger-clippers den)
  (at-location first-floor-to-landing-stairwell townhome)
  (at-location garage townhome)
  (at-location garage-entry-way townhome)
  (at-location guest-bathroom townhome)
  (at-location guestbed bedroom)
  (at-location kitchen townhome)
  (at-location kitchen-closet townhome)
  (at-location kitchen-outlets kitchen)
  (at-location landing townhome)
  (at-location landing-closet townhome)
  (at-location landing-to-second-floor-stairwell townhome)
  (at-location laptop-backpack den)
  (at-location laundry-load bedroom)
  (at-location living-room townhome)
  (at-location second-floor-landing townhome)
  (at-location towel-1 bedroom)
  (at-location towel-2 bedroom)
  (at-location towel-3 bedroom)
  (at-location upstairs-bathroom townhome)
  (at-location upstairs-bathroom-outlets upstairs-bathroom)
  (at-location upstairs-dryer utility-room)
  (at-location upstairs-shower upstairs-bathroom)
  (at-location upstairs-washer utility-room)
  (at-location utility-room townhome)
  (autonomous andrew-dougherty)
  (day-of-week date-20120821 Tuesday)
  (day-of-week date-20120822 Wednesday)
  (day-of-week date-20120823 Thursday)
  (day-of-week date-20120824 Friday)
  (day-of-week date-20120825 Saturday)
  (day-of-week date-20120826 Sunday)
  (day-of-week date-20120827 Monday)
  (dirty clothing-blue-shirt-1)
  (dirty clothing-green-shirt-1)
  (dirty clothing-grey-shirt-1)
  (dirty clothing-grey-shirt-2)
  (dirty clothing-khaki-shorts-1)
  (dirty clothing-khaki-shorts-2)
  (dirty den)
  (dirty garage)
  (dirty towel-1)
  (dirty towel-2)
  (dirty towel-3)
  (dirty upstairs-bathroom)
  (exhausted andrew-dougherty)
  (has-door balcony-door balcony dining-room)
  (has-door basement-door garage garage-entry-way)
  (has-door crawl-space-door crawl-space garage-entry-way)
  (has-door den-door den garage-entry-way)
  (has-door front-door entry outside)
  (has-door garage-door garage outside)
  (has-permission-to-use Andrew-Dougherty upstairs-bathroom)
  (locked-door basement-door)
  (locked-door front-door)
  (locked-door garage-door)
  (mobile bluetooth-headset)
  (mobile cell-phone)
  (mobile clothing-blue-shirt-1)
  (mobile clothing-green-shirt-1)
  (mobile clothing-grey-shirt-1)
  (mobile clothing-grey-shirt-2)
  (mobile clothing-khaki-shorts-1)
  (mobile clothing-khaki-shorts-2)
  (mobile columcille-computer)
  (mobile electric-razor-0)
  (mobile finger-clippers)
  (mobile laptop-backpack)
  (mobile laundry-load)
  (mobile towel-1)
  (mobile towel-2)
  (mobile towel-3)
  (plugged-in dennis-computer)
  (wearing Andrew-Dougherty clothing-grey-shirt-1)
  (wearing Andrew-Dougherty clothing-khaki-shorts-1)
  (weekday date-20120821)
  (weekday date-20120822)
  (weekday date-20120823)
  (weekday date-20120824)
  (weekday date-20120825))
 (:goal
  (and
   (location-is-clean townhome))))